mediawiki:
  #image: mediawiki
  build: .
  volumes:
   - wikidata:/var/wikidata
  ports:
   - "80:80"
  environment:
   - WIKI_URL=http://localhost
   - WIKI_DB_HOST=localhost
   - WIKI_DB_NAME=wikidb
   - WIKI_DB_USER=wikiuser
   - WIKI_DB_PASS=wikipass
